// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDStore.Data;

#nullable disable

namespace SDStore.Data.Migrations
{
    [DbContext(typeof(SDStoreDBContext))]
    partial class SDStoreDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SDStore.Data.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Items", t =>
                        {
                            t.HasCheckConstraint("CK_Item_PriceMode_AllowedCurrencies", "[PriceMode] IN ('PerItem', 'PerKg', 'PerLiter')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "LRAD model Vučić",
                            Price = "{\"Amount\":10464.95,\"Currency\":\"EUR\"}",
                            PriceMode = "PerItem"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bayraktar TB2",
                            Price = "{\"Amount\":7000000.00,\"Currency\":\"USD\"}",
                            PriceMode = "PerItem"
                        },
                        new
                        {
                            Id = 3,
                            Name = "F-16 Block 70",
                            Price = "{\"Amount\":150000000.00,\"Currency\":\"USD\"}",
                            PriceMode = "PerItem"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Uaz 469 restored",
                            Price = "{\"Amount\":10500.00,\"Currency\":\"BGN\"}",
                            PriceMode = "PerItem"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Simson S50",
                            Price = "{\"Amount\":2999.00,\"Currency\":\"BGN\"}",
                            PriceMode = "PerItem"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cyanide",
                            Price = "{\"Amount\":1250.00,\"Currency\":\"USD\"}",
                            PriceMode = "PerKg"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Novichok Agent",
                            Price = "{\"Amount\":23500.50,\"Currency\":\"BGN\"}",
                            PriceMode = "PerKg"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Bulk 7.62x39mm Ammo (AR-M1)",
                            Price = "{\"Amount\":1755.00,\"Currency\":\"BGN\"}",
                            PriceMode = "PerKg"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ballistic Alloy Powder (Training Grade)",
                            Price = "{\"Amount\":1200.00,\"Currency\":\"CAD\"}",
                            PriceMode = "PerKg"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Zimmerit (Anti‑Magnetic Armor Coating)",
                            Price = "{\"Amount\":250.50,\"Currency\":\"EUR\"}",
                            PriceMode = "PerKg"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Mustard Gas",
                            Price = "{\"Amount\":211.20,\"Currency\":\"EUR\"}",
                            PriceMode = "PerLiter"
                        },
                        new
                        {
                            Id = 12,
                            Name = "JP-8 Kerosene",
                            Price = "{\"Amount\":14308.83,\"Currency\":\"USD\"}",
                            PriceMode = "PerLiter"
                        },
                        new
                        {
                            Id = 13,
                            Name = "HFD-R: Phosphoric esters (Fire Resistant)",
                            Price = "{\"Amount\":1442.10,\"Currency\":\"BGN\"}",
                            PriceMode = "PerLiter"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Ricin",
                            Price = "{\"Amount\":419.30,\"Currency\":\"USD\"}",
                            PriceMode = "PerLiter"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Sarin",
                            Price = "{\"Amount\":761.50,\"Currency\":\"GBP\"}",
                            PriceMode = "PerLiter"
                        });
                });

            modelBuilder.Entity("SDStore.Data.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total_Gross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total_Net")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total_VAT_Excluded")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders", t =>
                        {
                            t.HasCheckConstraint("CK_Order_Currency_AllowedCurrencies", "[Currency] IN ('BGN', 'EUR', 'USD', 'CAD', 'GBP')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("32b00f9f-1b95-412a-8517-678c49419467"),
                            Address = "123 Maplewood Avenue, Apt 4B, Example City, CA 90001",
                            Currency = "BGN",
                            Email = "todor.jivkov@prb.bg",
                            PhoneNumber = "+1 (555) 010-0001",
                            Total_Gross = 4029616498.00m,
                            Total_Net = 3504013748.33m,
                            Total_VAT_Excluded = 525602749.67m
                        },
                        new
                        {
                            Id = new Guid("c131cb5b-acb4-479b-9dea-fedb9f52aef4"),
                            Address = "45 Riverside Drive, Example Town, NY 10010",
                            Currency = "USD",
                            Email = "vlad.putin@ussr.ru",
                            PhoneNumber = "+1 (555) 010-0002",
                            Total_Gross = 5381.97m,
                            Total_Net = 4646.64m,
                            Total_VAT_Excluded = 735.33m
                        },
                        new
                        {
                            Id = new Guid("24a2c27a-298c-4eea-bbd9-ffa832e9a697"),
                            Address = "789 Oak Street, Suite 210, Demo City, TX 73301",
                            Currency = "EUR",
                            Email = "austrian-painter@thirdreich.de",
                            PhoneNumber = "+1 (555) 010-0003",
                            Total_Gross = 12314930750.70m,
                            Total_Net = 11596249563.48m,
                            Total_VAT_Excluded = 718681187.22m
                        },
                        new
                        {
                            Id = new Guid("920c12b3-52da-409d-833f-109f8ee0147a"),
                            Address = "16 Pinecrest Road, Sampleville, WA 98001",
                            Currency = "GBP",
                            Email = "zelensky@example.ua",
                            PhoneNumber = "+1 (555) 010-0004",
                            Total_Gross = 283997879.16m,
                            Total_Net = 248286392.05m,
                            Total_VAT_Excluded = 35711487.11m
                        });
                });

            modelBuilder.Entity("SDStore.Data.Entities.OrderItem", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SubTotal_Gross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubTotal_Net")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VAT_Excluded")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VAT_Percentage")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("ItemId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", t =>
                        {
                            t.HasCheckConstraint("CK_OrderItem_Currency_AllowedCurrencies", "[Currency] IN ('BGN', 'EUR', 'USD', 'CAD', 'GBP')");

                            t.HasCheckConstraint("CK_OrderItem_VAT_Percentage_AllowedPercentages", "[VAT_Percentage] >= 0.00 AND [VAT_Percentage] <= 27.00");
                        });

                    b.HasData(
                        new
                        {
                            ItemId = 4,
                            OrderId = new Guid("32b00f9f-1b95-412a-8517-678c49419467"),
                            Amount = 1m,
                            Currency = "BGN",
                            SubTotal_Gross = 10500.00m,
                            SubTotal_Net = 8750.00m,
                            VAT_Excluded = 1750.00m,
                            VAT_Percentage = 20.00m
                        },
                        new
                        {
                            ItemId = 5,
                            OrderId = new Guid("32b00f9f-1b95-412a-8517-678c49419467"),
                            Amount = 2m,
                            Currency = "BGN",
                            SubTotal_Gross = 5998.00m,
                            SubTotal_Net = 4998.33m,
                            VAT_Excluded = 999.67m,
                            VAT_Percentage = 20.00m
                        },
                        new
                        {
                            ItemId = 3,
                            OrderId = new Guid("32b00f9f-1b95-412a-8517-678c49419467"),
                            Amount = 16m,
                            Currency = "BGN",
                            SubTotal_Gross = 4029600000.00m,
                            SubTotal_Net = 3504000000.00m,
                            VAT_Excluded = 525600000.00m,
                            VAT_Percentage = 15.00m
                        },
                        new
                        {
                            ItemId = 14,
                            OrderId = new Guid("c131cb5b-acb4-479b-9dea-fedb9f52aef4"),
                            Amount = 0.72m,
                            Currency = "USD",
                            SubTotal_Gross = 301.90m,
                            SubTotal_Net = 276.97m,
                            VAT_Excluded = 24.93m,
                            VAT_Percentage = 9.00m
                        },
                        new
                        {
                            ItemId = 15,
                            OrderId = new Guid("c131cb5b-acb4-479b-9dea-fedb9f52aef4"),
                            Amount = 2.11m,
                            Currency = "USD",
                            SubTotal_Gross = 2140.76m,
                            SubTotal_Net = 1960.40m,
                            VAT_Excluded = 180.36m,
                            VAT_Percentage = 9.20m
                        },
                        new
                        {
                            ItemId = 7,
                            OrderId = new Guid("c131cb5b-acb4-479b-9dea-fedb9f52aef4"),
                            Amount = 0.21m,
                            Currency = "USD",
                            SubTotal_Gross = 2939.31m,
                            SubTotal_Net = 2409.27m,
                            VAT_Excluded = 530.04m,
                            VAT_Percentage = 22.00m
                        },
                        new
                        {
                            ItemId = 10,
                            OrderId = new Guid("24a2c27a-298c-4eea-bbd9-ffa832e9a697"),
                            Amount = 10000.00m,
                            Currency = "EUR",
                            SubTotal_Gross = 25050000.00m,
                            SubTotal_Net = 23857142.86m,
                            VAT_Excluded = 1192857.14m,
                            VAT_Percentage = 5.00m
                        },
                        new
                        {
                            ItemId = 11,
                            OrderId = new Guid("24a2c27a-298c-4eea-bbd9-ffa832e9a697"),
                            Amount = 30000.00m,
                            Currency = "EUR",
                            SubTotal_Gross = 6336000.00m,
                            SubTotal_Net = 5966101.69m,
                            VAT_Excluded = 369898.31m,
                            VAT_Percentage = 6.20m
                        },
                        new
                        {
                            ItemId = 12,
                            OrderId = new Guid("24a2c27a-298c-4eea-bbd9-ffa832e9a697"),
                            Amount = 999999.99m,
                            Currency = "EUR",
                            SubTotal_Gross = 12283544750.70m,
                            SubTotal_Net = 11566426318.93m,
                            VAT_Excluded = 717118431.77m,
                            VAT_Percentage = 12.40m
                        },
                        new
                        {
                            ItemId = 2,
                            OrderId = new Guid("920c12b3-52da-409d-833f-109f8ee0147a"),
                            Amount = 15.00m,
                            Currency = "GBP",
                            SubTotal_Gross = 78808672.33m,
                            SubTotal_Net = 71644247.57m,
                            VAT_Excluded = 7164424.76m,
                            VAT_Percentage = 10.00m
                        },
                        new
                        {
                            ItemId = 8,
                            OrderId = new Guid("920c12b3-52da-409d-833f-109f8ee0147a"),
                            Amount = 100000.00m,
                            Currency = "GBP",
                            SubTotal_Gross = 78453285.65m,
                            SubTotal_Net = 64305971.84m,
                            VAT_Excluded = 14147313.81m,
                            VAT_Percentage = 22.00m
                        },
                        new
                        {
                            ItemId = 12,
                            OrderId = new Guid("920c12b3-52da-409d-833f-109f8ee0147a"),
                            Amount = 10000.00m,
                            Currency = "GBP",
                            SubTotal_Gross = 107396180.46m,
                            SubTotal_Net = 95548203.26m,
                            VAT_Excluded = 11847977.20m,
                            VAT_Percentage = 12.40m
                        },
                        new
                        {
                            ItemId = 13,
                            OrderId = new Guid("920c12b3-52da-409d-833f-109f8ee0147a"),
                            Amount = 30000.00m,
                            Currency = "GBP",
                            SubTotal_Gross = 19339740.72m,
                            SubTotal_Net = 16787969.38m,
                            VAT_Excluded = 2551771.34m,
                            VAT_Percentage = 15.20m
                        });
                });

            modelBuilder.Entity("SDStore.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("SDStore.Data.Entities.Item", "Item")
                        .WithMany("Orders")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SDStore.Data.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SDStore.Data.Entities.Item", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SDStore.Data.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
